# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20161123_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='vendor_code',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
