# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-14 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_position_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='catalog_name',
            field=models.CharField(default='', max_length=2**10 - 1),
        ),
        migrations.AddField(
            model_name='position',
            name='code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='position',
            name='url',
            field=models.CharField(default='', max_length=2**10 - 1),
        ),
    ]
