# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 11:00
# TODO need squashing this migration https://goo.gl/aohgCq
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20160909_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='title',
            new_name='_title',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='_h1',
            new_name='h1',
        ),
    ]
