# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-10 15:02
# TODO need squashing this migration https://goo.gl/aohgCq
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_db_refactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='_parent',
        ),
        migrations.RemoveField(
            model_name='page',
            name='route',
        ),
    ]
