# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-17 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_redundant_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='_menu_title',
            new_name='menu_title',
        ),
        migrations.AlterField(
            model_name='page',
            name='menu_title',
            field=models.CharField(blank=True, help_text='This field will be shown in the breadcrumbs, menu items and etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='h1',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
