# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-20 09:14
from __future__ import unicode_literals

from django.db import migrations

from pages.models import Page



def rebuild_tree(apps, schema_editor):
    Page.objects.rebuild()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_pages_mptt'),
    ]

    operations = [
        migrations.RunPython(rebuild_tree),
    ]
