# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-24 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_rebuild_pages_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
