# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_title_to_text_field'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='page',
            managers=[
            ],
        ),
    ]
