# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def migrate_forward(apps, schema_editor):
    PageTemplate = apps.get_model('pages', 'PageTemplate')
    PageTemplate.objects.create(
        name='Базовый шаблон страницы',
        title='{{ page.name }}',
    )


def migrate_backward(apps, schema_editor):
    PageTemplate = apps.get_model('pages', 'PageTemplate')
    PageTemplate.objects.get(id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20170317_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('h1', models.CharField(blank=True, max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='keywords')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('title', models.TextField(blank=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'PageTemplate',
                'verbose_name_plural': 'PageTemplates',
            },
        ),
        migrations.RemoveField(
            model_name='page',
            name='description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='h1',
        ),
        migrations.RemoveField(
            model_name='page',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='page',
            name='seo_text',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.PageTemplate', verbose_name='page template'),
        ),
        migrations.RunPython(migrate_forward, migrate_backward),
    ]
