# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20170317_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('h1', models.CharField(blank=True, max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='keywords')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('title', models.TextField(blank=True, verbose_name='title')),
                ('seo_text', models.TextField(blank=True, verbose_name='seo text')),
            ],
            options={
                'verbose_name': 'Page Template',
                'verbose_name_plural': 'Page Templates',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.PageTemplate', verbose_name='page template'),
        ),
    ]
