# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-16 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20170504_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetemplate',
            name='description',
            field=models.TextField(blank=True, validators=[pages.models.validate_template], verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='h1',
            field=models.CharField(blank=True, max_length=255, validators=[pages.models.validate_template]),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, validators=[pages.models.validate_template], verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='seo_text',
            field=models.TextField(blank=True, validators=[pages.models.validate_template], verbose_name='seo text'),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='title',
            field=models.TextField(blank=True, validators=[pages.models.validate_template], verbose_name='title'),
        ),
    ]
