# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-15 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_name_fields_increase_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetemplate',
            name='h1',
            field=models.CharField(blank=True, max_length=1000, validators=[pages.models.validate_template]),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000, validators=[pages.models.validate_template], verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='pagetemplate',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
