# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('h1', models.CharField(blank=True, max_length=100, null=True)),
                ('_menu_title', models.CharField(blank=True, max_length=30, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date_published', models.DateField(auto_now_add=True, null=True)),
                ('type', models.CharField(choices=[('news', 'Новости'), ('navigation', 'Частые вопросы'), ('article', 'Статьи')], default='navigation', max_length=100)),
                ('slug', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
