# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160418_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('news', 'Новости'), ('article', 'Статьи'), ('navigation', 'Навигация')], default='article', max_length=100),
        ),
    ]
