# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160513_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('news', 'Новости'), ('navigation', 'Навигация'), ('article', 'Статьи')], default='article', max_length=100),
        ),
    ]
