# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160524_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('article', 'Статьи'), ('news', 'Новости'), ('navigation', 'Навигация')], default='article', max_length=100),
        ),
    ]
