# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160524_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data_published',
            new_name='date_published',
        ),
        migrations.AddField(
            model_name='post',
            name='_menu_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('news', 'Новости'), ('navigation', 'Навигация'), ('article', 'Статьи')], default='article', max_length=100),
        ),
    ]
