# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160524_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('navigation', 'Навигация'), ('news', 'Новости'), ('article', 'Статьи')], default='article', max_length=100),
        ),
    ]
