# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-28 09:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models
from sorl import thumbnail


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('_title', models.CharField(blank=True, default='', max_length=400)),
                ('slug', models.SlugField(blank=True, max_length=400)),
                ('description', models.TextField(default='')),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
                ('image', thumbnail.fields.ImageField()),
                ('is_main', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
