# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-27 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
