# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20160909_0755'),
        ('catalog', '0003_auto_20160906_1631'),
    ]

    operations = [
    ]
