# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-11 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_add_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mockcategorywithdefaultpage',
            name='name',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mockecommercecategory',
            name='name',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mocktag',
            name='name',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='name'),
        ),
    ]
