# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-13 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_buff_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktag',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='mocktag',
            unique_together=set([('slug', 'group'), ('name', 'group')]),
        ),
    ]
