# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-10 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_fix_tag_slug_uniqueness'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mockecommerceproduct',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mockproduct',
            options={},
        ),
        migrations.AddField(
            model_name='mockproduct',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='tests.MockTag', verbose_name='tags'),
        ),
    ]
