# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS pg_trgm;'),
        # By default, tables (and other objects) are automatically put into
        # a schema named "public".
        migrations.RunSQL('ALTER EXTENSION pg_trgm SET SCHEMA public;'),
    ]
